[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48082
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Core Command Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-core-command.log'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061
