[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48081
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the EdgeX Core Metadata Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-core-metadata.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'metadata.db'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'boltdb'

[Notifications]
PostDeviceChanges = false
Slug = 'device-change-'
Content = 'Device update: '
Sender = 'core-metadata'
Description = 'Metadata device notice'
Label = 'metadata'
