[Writable]
DeviceUpdateLastConnected = true
MetaDataCheck = false
PersistData = false
ServiceUpdateLastConnected = false
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48080
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Core Data Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-core-data.log'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'coredata.db'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'boltdb'

[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
