ScheduleInterval = 500

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = './logs/edgex-support-scheduler.log'
Level = 'INFO'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Schedules]
    [Schedules.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = 'P1D'

    [Schedules.EveryHour_EDS]
    Name = 'schedule-everyhour-eds'
    Start = '20190101T000000'
    Frequency = 'PT1H'

[ScheduleEvents]
    [ScheduleEvents.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/scrub'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'

    [ScheduleEvents.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'

    [ScheduleEvents.ScrubAged1DayLogsEDS]
    Name = 'scrub-aged1day-logs-eds'
    Host = 'localhost'
    Port = 48061
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'support-logging'
    Path = '/api/v1/logs/removeold/age/86400000'
    Schedule = 'schedule-everyhour-eds'
    Scheduler = 'support-scheduler'
