linters:
  enable:
    - depguard
    - dogsled
    - gochecknoinits
    - gofmt
    - goimports
    - interfacer
    - staticcheck
  disable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - golint
    - gosec
    - gosimple
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - stylecheck
    - unparam
    - wsl
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1029:"