linters:
  enable:
    - depguard
    - dogsled
    - gochecknoinits
    - gofmt
    - goimports
    - interfacer
  disable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - golint
    - gosec
    - gosimple
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - stylecheck
    - unparam
    - wsl
    - whitespace
