[Writable]
MarkPushed = false
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48070
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Export Distro Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-export-distro.log'

[Clients]
  [Clients.Export]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48071

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[Certificates]
  [Certificates.MQTTS]
  Cert = ""
  Key = ""

  [Certificates.GIOT]
  Cert = "./keys/giot_cert.pem"
  Key = "./keys/giot_private.pem"
  #Cert = "/etc/edgex/giot_cert.pem"
  #Key = "/etc/edgex/giot_private.pem"

  [Certificates.AWS]
  Cert = "./keys/aws_cert.pem"
  Key = "./keys/aws_private.pem"
  #Cert = "/etc/edgex/aws_cert.pem"
  #Key = "/etc/edgex/aws_private.pem"


[MessageQueue]
Protocol = 'tcp'
Host = 'localhost'
Port = 5563
Type = 'zero'

[AnalyticsQueue]
Protocol = 'tcp'
Host = '*'
Port = 5566
Type = 'zero'
