Hostname = '127.0.0.1'
Port = 48071
DBType = 'boltdb'
MongoURL = '0.0.0.0'
MongoUsername = ''
MongoPassword = ''
MongoDatabaseName = 'coredata'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost = 'localhost'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'go'
DistroHost = 'localhost'
DistroPort = 48070
