#!/bin/sh
if true && type update-rc.d >/dev/null 2>/dev/null; then
	if [ -n "$D" ]; then
		OPT="-r $D"
	else
		OPT="-s"
	fi
	update-rc.d $OPT edgex.sh start 80 5 .
	chown -R root:root /etc/edgex
	chown root:root /usr/bin/edgex
fi
