[Writable]
ScheduleIntervalTime = 500
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48085
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-support-scheduler.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'scheduler.db'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'boltdb'
