Hostname = 'localhost'
Port = 48061
Persistence = 'file'
LoggingFile = './logs/edgex.log'
MongoDB = 'logging'
MongoCollection = 'logEntry'
MongoURL = 'localhost'
MongoPort = 27017
MongoConnectTimeout = 5000
SocketTimeout = 5000
MongoUsername = ''
MongoPassword = ''
CheckInterval = '10s'
ConsulHost = 'localhost'
ConsulPort = 8500
ConsulProfilesActive = 'go'
