[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
Host = 'localhost'
Port = 48071
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Export Client Microservice'
Timeout = 5000

[Logging]
EnableRemote = true
File = './logs/edgex-export-client.log'

[Clients]
  [Clients.Distro]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48070

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'exportclient.db'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'boltdb'

